[package]
name = "pipgre"
version = "0.1.0"
authors = ["r_tsukamoto <r_tsukamoto@ill.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
structopt = "0.2"
atty = "0.2"
